import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-[#0a0a1a] selection:bg-[#1f1f69] selection:text-white">
        {/* Capa de ruido o grano sutil (opcional para el toque aesthetic) */}
        <div className="fixed inset-0 z-[-1] bg-[url('/noise.png')] opacity-[0.03] pointer-events-none"></div>
        
        {/* Luces de fondo fijas con tu color #1f1f69 */}
        <div className="fixed inset-0 z-[-2] overflow-hidden">
          <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] rounded-full bg-[#1f1f69] blur-[150px] opacity-20"></div>
          <div className="absolute top-[30%] -right-[10%] w-[35%] h-[35%] rounded-full bg-[#1f1f69] blur-[150px] opacity-10"></div>
          <div className="absolute -bottom-[10%] left-[20%] w-[50%] h-[50%] rounded-full bg-[#1f1f69] blur-[150px] opacity-15"></div>
        </div>

        {children}
      </body>
    </html>
  );
}
